variable "rgname" {}
variable "rglocation" {}
variable "prefix" {}
variable "vnet_cidr_prefix" {}
variable "subnet1_cidr_prefix" {}
variable "subnet2_cidr_prefix" {}
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}
variable "tags" {}